linters:
  ColorVariable:
    enabled: false
  DeclarationOrder:
    enabled: false
  DuplicateProperty:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  FinalNewline:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  Indentation:
    enabled: false
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: false
  NestingDepth:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: false
  PseudoElement:
    enabled: false
  QualifyingElement:
    enabled: false
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SpaceAroundOperator:
    enabled: false
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    enabled: false
  VendorPrefix:
    enabled: false
