source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

ruby '2.3.3'

# gem 'rails_12factor'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.5'
# Use sqlite3 as the database for Active Record
gem 'pg'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'activerecord-session_store'
gem 'airbrake', '5.8.0'
gem 'api_cache'
gem 'aws-sdk', '~> 2.3.0'
gem 'bootstrap-sass', '3.3.7'
gem 'devise'
gem 'figaro'
gem 'font-awesome-sass', '~> 4.7.0'
gem 'geokit-rails'
gem 'haml'
gem 'kaminari'
gem 'omniauth'
gem 'omniauth-facebook', '~> 4.0'
gem 'omniauth-google-oauth2'
gem 'omniauth-linkedin-oauth2'
gem 'paperclip', '~> 5.1.0'
gem 'rack-cors', require: 'rack/cors'
gem 'resque'
gem 'resque-scheduler'
gem 'safety_mailer'
gem 'simple-navigation'
gem 'simple-navigation-bootstrap'
gem 'sortable-table', github: 'caselle/sortable-table'
gem 'stripe'
gem 'twilio-ruby'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'factory_girl_rails'
  gem 'haml_lint'
  gem 'rspec-rails'
  gem 'rubocop'
  gem 'scss_lint', '0.52.0', require: false
  gem 'simplecov', require: false
  gem 'thor'
end

group :test do
  gem 'rails-controller-testing'
  gem 'shoulda'
  gem 'stripe-ruby-mock'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'listen', '~> 3.0.5'
  gem 'web-console', '>= 3.3.0'

  gem 'seed_dump'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
