# Add configuration values here, as shown below.

development:
  AIRBRAKE_API_KEY:
  AIRBRAKE_PROJECT_ID:
  AWS_REGION:
  AWS_S3_REGION:
  AWS_S3_BUCKET:
  AWS_ACCESS_KEY_ID:
  AWS_ACCESS_KEY_SECRET:
  FACEBOOK_APP_ID:
  FACEBOOK_APP_SECRET:
  LINKED_IN_APP_ID:
  LINKED_IN_APP_SECRET:
  GOOGLE_APP_ID:
  GOOGLE_APP_SECRET:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  STRIPE_PUBLISHABLE_KEY:
  STRIPE_SECRET_KEY:
  COUNTRY_CODE:
  TWILIO_ACCOUNT_SID:
  TWILIO_AUTH_TOKEN:
  TWILIO_NUMBER:

test:
  AIRBRAKE_API_KEY:
  AIRBRAKE_PROJECT_ID:
  AWS_REGION:
  AWS_S3_REGION:
  AWS_S3_BUCKET:
  AWS_ACCESS_KEY_ID:
  AWS_ACCESS_KEY_SECRET:
  FACEBOOK_APP_ID:
  FACEBOOK_APP_SECRET:
  LINKED_IN_APP_ID:
  LINKED_IN_APP_SECRET:
  GOOGLE_APP_ID:
  GOOGLE_APP_SECRET:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  STRIPE_PUBLISHABLE_KEY:
  STRIPE_SECRET_KEY:
  COUNTRY_CODE:
  TWILIO_ACCOUNT_SID:
  TWILIO_AUTH_TOKEN:
  TWILIO_NUMBER:

production:
  AIRBRAKE_API_KEY:
  AIRBRAKE_PROJECT_ID:
  AWS_REGION:
  AWS_S3_REGION:
  AWS_S3_BUCKET:
  AWS_ACCESS_KEY_ID:
  AWS_ACCESS_KEY_SECRET:
  FACEBOOK_APP_ID:
  FACEBOOK_APP_SECRET:
  LINKED_IN_APP_ID:
  LINKED_IN_APP_SECRET:
  GOOGLE_APP_ID:
  GOOGLE_APP_SECRET:
  SENDGRID_USERNAME:
  SENDGRID_PASSWORD:
  STRIPE_PUBLISHABLE_KEY:
  STRIPE_SECRET_KEY:
  COUNTRY_CODE:
  TWILIO_ACCOUNT_SID:
  TWILIO_AUTH_TOKEN:
  TWILIO_NUMBER:
